import type { Page } from "playwright";
import { PlaywrightBrowserProvider } from "./playwright-browser-provider.js";
type Composer=ReturnType<Page["locator"]>;
const running=new WeakMap<Page,Promise<boolean>>();const results=new WeakMap<Page,boolean>();const composers=new WeakMap<Page,Composer>();
const isGithub=(s:string)=>/github|repositories|repos|pull requests|issues|commits|branches|仓库|代码仓库|拉取请求|分支|提交记录/i.test(s);
const chat=(p:Page)=>{try{const u=new URL(p.url());return u.protocol==="https:"&&(u.hostname==="chatgpt.com"||u.hostname==="chat.openai.com")&&!/^\/(apps|gpts)(?:\/|$)/i.test(u.pathname)}catch{return false}};
async function find(p:Page):Promise<Composer|undefined>{for(const s of ["[contenteditable='true']:not([aria-hidden='true'])","textarea[name='prompt-textarea']:not(.wcDTda_fallbackTextarea)","textarea:not(.wcDTda_fallbackTextarea)","[role='textbox']:not([aria-hidden='true'])"]){const n=p.locator(s);for(let i=await n.count()-1;i>=0;i--){const x=n.nth(i);if(await x.isVisible().catch(()=>false))return x}}return undefined}
async function wait(p:Page){const end=Date.now()+30000;while(Date.now()<end){if(!chat(p))return undefined;const c=await find(p);if(c)return c;await p.waitForTimeout(300)}return undefined}
async function selected(p:Page){return p.evaluate(()=>{const v=(n:HTMLElement)=>{const s=getComputedStyle(n),r=n.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&r.width>1&&r.height>1};const c=Array.from(document.querySelectorAll<HTMLElement>("[contenteditable='true'],textarea,[role='textbox']")).reverse().find(v);if(!c)return false;if(Array.from(c.querySelectorAll<HTMLElement>("[data-mention],[data-testid*='mention' i],[aria-label*='GitHub' i],[data-app-id*='github' i]")).some(v))return true;const t=`${c.textContent||""} ${(c as HTMLTextAreaElement).value||""}`;return /GitHub/i.test(t)&&!/@GitHub/i.test(t)&&!Array.from(document.querySelectorAll<HTMLElement>("[role='option'],[role='menuitem'],[role='listbox']")).some(v)}).catch(()=>false)}
async function choose(p:Page){const c=await wait(p);if(!c)return false;if(await selected(p)){composers.set(p,c);return true}await c.click({timeout:5000});await c.pressSequentially("@GitHub",{delay:25});await p.waitForTimeout(350);if(!chat(p))return false;await c.press("Space").catch(()=>undefined);await p.waitForTimeout(600);const ok=await selected(p);if(ok)composers.set(p,c);return ok}
export function ensureGitHubSelectedV2(p:Page,_app="GitHub"){const r=results.get(p);if(r!==undefined)return Promise.resolve(r);const a=running.get(p);if(a)return a;const q=choose(p).then(x=>{results.set(p,x);return x}).catch(()=>{results.set(p,false);return false}).finally(()=>running.delete(p));running.set(p,q);return q}
export async function submitMessageAfterGitHubSelection(p:Page,text:string){const c=composers.get(p)??await find(p);if(!c)throw new Error("ChatGPT composer is not available after selecting GitHub");await c.evaluate((n,t)=>{(n as HTMLElement).focus();document.execCommand("insertText",false,t)},text).catch(()=>c.pressSequentially(text,{delay:5}));for(const s of ['button[data-testid="send-button"]','button[aria-label*="Send" i]','button[aria-label*="发送" i]','button[type="submit"]']){const b=p.locator(s);for(let i=await b.count()-1;i>=0;i--){const x=b.nth(i);if(await x.isVisible().catch(()=>false)&&!await x.isDisabled().catch(()=>true)){await x.click({timeout:5000});return}}}await c.press("Enter")}
const pp=PlaywrightBrowserProvider.prototype as unknown as {sendMessage(id:string,text:string):Promise<void>;agents?:Map<string,{page:Page}>;__githubTx?:boolean};const native=pp.sendMessage;if(!pp.__githubTx){pp.__githubTx=true;pp.sendMessage=async function(id,text){if(!isGithub(text))return native.call(this,id,text);const a=this.agents?.get(id);if(!a)throw new Error(`Agent ${id} not found`);if(!await ensureGitHubSelectedV2(a.page))throw new Error("GitHub App initialization failed");await submitMessageAfterGitHubSelection(a.page,text)}}
