type ToolCall = { tool: string; arguments: Record<string, unknown> };
type ToolResult = { ok: boolean; result?: unknown; error?: string };
type RuntimeResponse = { result?: unknown; error?: { message?: string }; ok?: boolean };
type RuntimeToolDescription = { name: string; description?: string; inputSchema?: unknown };
type AgentEvent = { type: "state.changed" | "tool.call" | "tool.result"; state?: string; call?: ToolCall; result?: ToolResult; sessionId?: string };
type AssistantMessage = { text: string; node: HTMLElement };
type BridgeSnapshot = { composer: boolean; composerTag: string | null; sendButton: boolean; assistantCount: number; latestAssistantTextLength: number; activeElement: string | null; url: string };
const MAX_ROUNDS = 12;
const RESPONSE_TIMEOUT_MS = 120000;
const BRIDGE_TEST_TIMEOUT_MS = 15000;
const RPC_TIMEOUT_MS = 15000;
const SESSION_LOCK_KEY = "browser-coding-agent-active-session";
let running = false;
let activeSessionId: string | null = null;
function emit(event: AgentEvent): void { try { chrome.runtime.sendMessage({ type: "agent.event", params: event }, () => { void chrome.runtime.lastError; }); } catch { /* stale extension context */ } }
function runtimeRpc(message: Record<string, unknown>): Promise<RuntimeResponse> { return new Promise((resolve, reject) => { let settled = false; const finish = (fn: () => void) => { if (settled) return; settled = true; window.clearTimeout(timer); fn(); }; const timer = window.setTimeout(() => finish(() => reject(new Error("Timed out waiting for local Runtime"))), RPC_TIMEOUT_MS); try { chrome.runtime.sendMessage(message, (response: RuntimeResponse | undefined) => { if (chrome.runtime.lastError) { finish(() => reject(new Error(chrome.runtime.lastError?.message ?? "Extension message failed"))); return; } if (!response) { finish(() => reject(new Error("Extension returned no response"))); return; } finish(() => resolve(response)); }); } catch (error) { finish(() => reject(error instanceof Error ? error : new Error(String(error)))); } }); }
function visible<T extends HTMLElement>(nodes: T[]): T | null { return nodes.find((node) => { const rect = node.getBoundingClientRect(); return rect.width > 0 && rect.height > 0 && getComputedStyle(node).visibility !== "hidden"; }) ?? null; }
function getComposer(): HTMLTextAreaElement | HTMLElement | null { const active = document.activeElement; if (active instanceof HTMLElement && active.matches("[contenteditable='true'], [role='textbox']") && active.getBoundingClientRect().height > 0) return active; const editable = visible(Array.from(document.querySelectorAll<HTMLElement>("[contenteditable='true'][role='textbox'], [contenteditable='true']"))); if (editable) return editable; return visible(Array.from(document.querySelectorAll<HTMLTextAreaElement>("textarea"))); }
function setComposerValue(composer: HTMLTextAreaElement | HTMLElement, text: string): void { composer.focus(); if (composer instanceof HTMLTextAreaElement) { const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set; if (!setter) throw new Error("Unable to set ChatGPT composer value"); setter.call(composer, text); composer.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertText", data: text })); composer.dispatchEvent(new Event("change", { bubbles: true })); return; } const selection = window.getSelection(); const range = document.createRange(); range.selectNodeContents(composer); selection?.removeAllRanges(); selection?.addRange(range); document.execCommand("insertText", false, text); if ((composer.textContent ?? "") !== text) composer.textContent = text; composer.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertText", data: text })); }
function findSendButton(): HTMLButtonElement | null { const selectors = ['button[data-testid="send-button"]', 'button[aria-label*="Send" i]', 'button[type="submit"]', 'form button:not([disabled])']; for (const selector of selectors) { const buttons = Array.from(document.querySelectorAll<HTMLButtonElement>(selector)).filter((button) => !button.disabled); const button = visible(buttons); if (button) return button; } return null; }
async function submitToChatGPT(text: string): Promise<"button" | "enter"> { emit({ type: "state.changed", state: "submitting-prompt", sessionId: activeSessionId ?? undefined }); const composer = getComposer(); if (!composer) throw new Error("ChatGPT composer was not found. Open a normal ChatGPT conversation."); setComposerValue(composer, text); await new Promise((resolve) => setTimeout(resolve, 700)); const button = findSendButton(); if (button) { button.click(); emit({ type: "state.changed", state: "prompt-submitted", sessionId: activeSessionId ?? undefined }); return "button"; } const form = composer.closest("form"); if (form instanceof HTMLFormElement) { form.requestSubmit(); emit({ type: "state.changed", state: "prompt-submitted-form", sessionId: activeSessionId ?? undefined }); return "enter"; } composer.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", bubbles: true, cancelable: true })); await new Promise((resolve) => setTimeout(resolve, 100)); composer.dispatchEvent(new KeyboardEvent("keyup", { key: "Enter", code: "Enter", bubbles: true })); emit({ type: "state.changed", state: "prompt-submitted-enter", sessionId: activeSessionId ?? undefined }); return "enter"; }
function assistantMessages(): AssistantMessage[] { const roleNodes = Array.from(document.querySelectorAll<HTMLElement>("[data-message-author-role='assistant']")); if (roleNodes.length > 0) return roleNodes.map((node) => ({ text: node.innerText.trim(), node })).filter((item) => item.text.length > 0); return Array.from(document.querySelectorAll<HTMLElement>("article")).map((node) => ({ text: node.innerText.trim(), node })).filter((item) => item.text.length > 0); }
function snapshot(): BridgeSnapshot { const composer = getComposer(); const assistants = assistantMessages(); const active = document.activeElement; return { composer: Boolean(composer), composerTag: composer?.tagName ?? null, sendButton: Boolean(findSendButton()), assistantCount: assistants.length, latestAssistantTextLength: assistants.at(-1)?.text.length ?? 0, activeElement: active instanceof HTMLElement ? `${active.tagName}${active.getAttribute("role") ? `[role=${active.getAttribute("role")}]` : ""}` : null, url: location.href }; }
async function waitForAssistantResponse(previousNode: HTMLElement | null, previousText: string, timeoutMs = RESPONSE_TIMEOUT_MS): Promise<string> { emit({ type: "state.changed", state: "waiting-assistant", sessionId: activeSessionId ?? undefined }); const started = Date.now(); let lastText = ""; let stableSince = 0; while (Date.now() - started < timeoutMs) { const messages = assistantMessages(); const current = messages.at(-1); if (current) { const text = current.text; const isNewNode = current.node !== previousNode; const isChangedExistingNode = current.node === previousNode && text.length > previousText.length && text !== previousText; if ((isNewNode || isChangedExistingNode) && text) { if (text !== lastText) { lastText = text; stableSince = Date.now(); } if (Date.now() - stableSince >= 1200) return lastText; } } await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error(`Timed out waiting for ChatGPT response after ${Math.round(timeoutMs / 1000)}s`); }
function parseToolPlan(text: string): { calls: ToolCall[]; done: boolean } { const cleaned = text.replace(/```(?:json)?/gi, "").replace(/```/g, "").trim(); const candidates = [cleaned, cleaned.match(/\{[\s\S]*\}/)?.[0] ?? ""]; for (const candidate of candidates) { try { const value = JSON.parse(candidate) as { calls?: unknown; done?: unknown }; if (!Array.isArray(value.calls)) continue; const calls = value.calls.map((item, index) => { if (!item || typeof item !== "object") throw new Error(`Invalid tool call ${index + 1}`); const call = item as { tool?: unknown; arguments?: unknown }; if (typeof call.tool !== "string") throw new Error(`Tool call ${index + 1} has no tool name`); if (!call.arguments || typeof call.arguments !== "object" || Array.isArray(call.arguments)) throw new Error(`Arguments for ${call.tool} must be an object`); return { tool: call.tool, arguments: call.arguments as Record<string, unknown> }; }); return { calls, done: value.done === true || calls.length === 0 }; } catch { /* continue */ } } throw new Error("ChatGPT did not return the required JSON tool plan"); }
function plannerPrompt(goal: string, tools: RuntimeToolDescription[], history: Array<{ call: ToolCall; result: ToolResult }>): string { return ["You are the coding-agent planner operating in the user's logged-in ChatGPT browser session.", "The local computer is available only through the listed tools. Never claim local state that a tool result does not confirm.", "Plan only the NEXT batch of tool calls. Return JSON ONLY.", '{"done":true,"calls":[]} means complete; otherwise use {"done":false,"calls":[{"tool":"...","arguments":{}}]}.', `Goal: ${goal}`, `Available tools: ${JSON.stringify(tools)}`, `Execution history: ${JSON.stringify(history)}`].join("\n\n"); }
function finalPrompt(goal: string, history: Array<{ call: ToolCall; result: ToolResult }>): string { return ["The local Browser Coding Agent has finished executing tools for the user's request.", "Answer the original user normally, using only the execution history as evidence.", "Do not return JSON.", `Original goal: ${goal}`, `Execution history: ${JSON.stringify(history)}`].join("\n\n"); }
function readLock(): { sessionId: string; startedAt: number } | null { try { const raw = sessionStorage.getItem(SESSION_LOCK_KEY); if (!raw) return null; const parsed = JSON.parse(raw) as { sessionId?: unknown; startedAt?: unknown }; if (typeof parsed.sessionId !== "string" || typeof parsed.startedAt !== "number") return null; if (Date.now() - parsed.startedAt > 10 * 60 * 1000) { sessionStorage.removeItem(SESSION_LOCK_KEY); return null; } return { sessionId: parsed.sessionId, startedAt: parsed.startedAt }; } catch { return null; } }
function acquireSession(): string { const existing = readLock(); if (existing) throw new Error(`Agent already running (session ${existing.sessionId})`); const sessionId = crypto.randomUUID(); sessionStorage.setItem(SESSION_LOCK_KEY, JSON.stringify({ sessionId, startedAt: Date.now() })); activeSessionId = sessionId; return sessionId; }
function releaseSession(sessionId: string): void { try { const current = readLock(); if (current?.sessionId === sessionId) sessionStorage.removeItem(SESSION_LOCK_KEY); } catch { /* ignore */ } if (activeSessionId === sessionId) activeSessionId = null; }
async function runAgent(workspace: string, goal: string, sessionId: string): Promise<void> { if (running) return; running = true; emit({ type: "state.changed", state: "task.started", sessionId }); emit({ type: "state.changed", state: "planning", sessionId }); try { emit({ type: "state.changed", state: "workspace-select", sessionId }); const selected = await runtimeRpc({ jsonrpc: "2.0", id: crypto.randomUUID(), method: "workspace.select", params: { path: workspace } }); if (selected.error) throw new Error(selected.error.message ?? "Workspace selection failed"); emit({ type: "state.changed", state: "tools-list", sessionId }); const toolsResponse = await runtimeRpc({ jsonrpc: "2.0", id: crypto.randomUUID(), method: "tools.list" }); if (toolsResponse.error) throw new Error(toolsResponse.error.message ?? "Unable to list tools"); const tools: RuntimeToolDescription[] = Array.isArray(toolsResponse.result) ? toolsResponse.result as RuntimeToolDescription[] : []; const history: Array<{ call: ToolCall; result: ToolResult }> = []; for (let round = 0; round < MAX_ROUNDS; round += 1) { const previous = assistantMessages().at(-1); await submitToChatGPT(plannerPrompt(goal, tools, history)); const responseText = await waitForAssistantResponse(previous?.node ?? null, previous?.text ?? ""); const plan = parseToolPlan(responseText); if (plan.done) { const finalPrevious = assistantMessages().at(-1); await submitToChatGPT(finalPrompt(goal, history)); const finalText = await waitForAssistantResponse(finalPrevious?.node ?? null, finalPrevious?.text ?? ""); emit({ type: "tool.result", result: { ok: true, result: { phase: "final-response", text: finalText, history } }, sessionId }); emit({ type: "state.changed", state: "completed", sessionId }); return; } emit({ type: "state.changed", state: "inspecting", sessionId }); for (const call of plan.calls) { emit({ type: "tool.call", call, sessionId }); const response = await runtimeRpc({ jsonrpc: "2.0", id: crypto.randomUUID(), method: "tool.call", params: { call } }); const result: ToolResult = response.error ? { ok: false, error: response.error.message ?? "Runtime tool call failed" } : response.result as ToolResult; history.push({ call, result }); emit({ type: "tool.result", call, result, sessionId }); } emit({ type: "state.changed", state: "planning", sessionId }); } throw new Error(`Agent stopped after ${MAX_ROUNDS} planning rounds`); } finally { running = false; releaseSession(sessionId); emit({ type: "state.changed", state: "task.ended", sessionId }); } }
try { chrome.runtime.onMessage.addListener((message: unknown, _sender, sendResponse) => { if (!message || typeof message !== "object") return false; const request = message as Record<string, unknown>; if (request.type === "chatgpt.ping") { sendResponse({ ok: true }); return false; } if (request.type === "chatgpt.bridge.diagnostic") { sendResponse({ ok: true, diagnostic: snapshot() }); return false; } if (request.type === "chatgpt.bridge.test") { void (async () => { const before = snapshot(); emit({ type: "state.changed", state: "bridge-test" }); emit({ type: "tool.result", result: { ok: true, result: { phase: "before", snapshot: before } } }); try { const previous = assistantMessages().at(-1); const submitMethod = await submitToChatGPT("Please reply with exactly BROWSER_AGENT_BRIDGE_OK and nothing else."); emit({ type: "tool.result", result: { ok: true, result: { phase: "submitted", submitMethod, snapshot: snapshot() } } }); const text = await waitForAssistantResponse(previous?.node ?? null, previous?.text ?? "", BRIDGE_TEST_TIMEOUT_MS); emit({ type: "state.changed", state: "bridge-test-passed" }); emit({ type: "tool.result", result: { ok: true, result: { phase: "after", text, snapshot: snapshot() } } }); } catch (error) { emit({ type: "state.changed", state: "bridge-test-failed" }); emit({ type: "tool.result", result: { ok: false, error: error instanceof Error ? error.message : String(error), result: { phase: "failed", snapshot: snapshot() } } }); } })(); sendResponse({ ok: true }); return false; } if (request.type !== "chatgpt.start") return false; const workspace = typeof request.workspace === "string" ? request.workspace : ""; const goal = typeof request.goal === "string" ? request.goal : ""; if (!workspace || !goal) { sendResponse({ ok: false, error: "Workspace and goal are required" }); return false; } let sessionId: string; try { sessionId = acquireSession(); } catch (error) { const message = error instanceof Error ? error.message : String(error); emit({ type: "state.changed", state: "task.rejected" }); emit({ type: "tool.result", result: { ok: false, error: message } }); sendResponse({ ok: false, error: message }); return false; } void runAgent(workspace, goal, sessionId).catch((error: unknown) => { emit({ type: "state.changed", state: "failed", sessionId }); emit({ type: "tool.result", result: { ok: false, error: error instanceof Error ? error.message : String(error) }, sessionId }); }); sendResponse({ ok: true, sessionId }); return false; }); } catch { /* stale extension context */ }
export {};
